add_executable(boolean-uv-benchmark boolean-uv.cpp boolean-uv-prepare.cpp boolean-uv-filter.cpp)
target_include_directories(boolean-uv-benchmark PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/..)
target_include_directories(boolean-uv-benchmark SYSTEM PRIVATE ${OpenCASCADE_INCLUDE_DIR} ${BOOST_INCLUDE_DIR})
target_link_libraries(boolean-uv-benchmark PRIVATE TKPrim TKShHealing TKBO TKBool TKTopAlgo TKGeomAlgo TKGeomBase TKBRep TKG3d TKG2d TKMath TKernel)
target_link_options(boolean-uv-benchmark PRIVATE "$<$<PLATFORM_ID:Linux>:-Wl,--disable-new-dtags>")
