import type { DocumentOwner } from "../src/backend/document-owner.js";
import type { Body } from "../src/model/body.js";
import { sphereFit } from "./mesh-fit-fixtures.js";
import { smoothShape } from "./mesh-fit-shapes.js";

/** Independent freeform supports; these are not generated by the erosion fallback. */
export async function erosionReconstructionSource(
  owner: DocumentOwner,
  kind: "waist" | "sphere" = "waist",
): Promise<Body> {
  const input =
    kind === "sphere"
      ? sphereFit()
      : smoothShape(
          ([x, y, z]) => [8 * x * (0.65 + 0.35 * z * z), 8 * y * (0.65 + 0.35 * z * z), 15 * z],
          3,
        );
  owner.beginScript(`erosion-${kind}.ts`);
  await owner.scripts.step({ kind: "fitMesh", input });
  owner.scripts.finish();
  const body = owner.view.data.bodies?.at(-1);
  if (!body) throw new Error("Freeform source did not produce a body");
  return body;
}

/** Independent meridian integration of the ideal source's inward parallel surface. */
export function waistInteriorVolume(depth: number): number {
  let radius = 0,
    height = 15 - depth,
    volume = 0;
  for (let i = 1; i <= 2000; i++) {
    const angle = (i * Math.PI) / 4000,
      s = Math.sin(angle),
      c = Math.cos(angle);
    const dr = 8 * c * (-0.05 + 1.05 * c * c),
      dz = -15 * s;
    const speed = Math.hypot(dr, dz);
    const nextRadius = 8 * s * (0.65 + 0.35 * c * c) + (depth * dz) / speed;
    const nextHeight = 15 * c - (depth * dr) / speed;
    volume +=
      (Math.PI *
        (height - nextHeight) *
        (radius * radius + radius * nextRadius + nextRadius * nextRadius)) /
      3;
    radius = nextRadius;
    height = nextHeight;
  }
  return 2 * volume;
}
