function(verify_web_sdk)
  set(sdk "${OpenCASCADE_INSTALL_PREFIX}")
  if(NOT EXISTS "${sdk}/.makeshift-web-sdk")
    message(FATAL_ERROR "Run npm run build:wasm to prepare the adapted WASM SDK")
  endif()
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
  set(inputs "")
  foreach(path scripts/web/build-wasm.mjs scripts/web/sdk.mjs scripts/occt-source.mjs scripts/occt-recipe.json native/web/verify-sdk.cmake)
    file(SHA256 "${root}/${path}" hash)
    string(APPEND inputs "${path}:${hash}\n")
  endforeach()
  string(SHA256 expected_recipe "${inputs}")
  file(STRINGS "${sdk}/.makeshift-web-sdk" receipt)
  list(GET receipt 0 recipe)
  list(GET receipt 1 manifest_hash)
  file(SHA256 "${sdk}/.makeshift-web-files" actual_manifest)
  if(NOT recipe STREQUAL expected_recipe OR NOT manifest_hash STREQUAL actual_manifest)
    message(FATAL_ERROR "WASM SDK recipe differs from this checkout; run npm run build:wasm")
  endif()
  file(STRINGS "${sdk}/.makeshift-web-files" entries)
  foreach(entry IN LISTS entries)
    string(SUBSTRING "${entry}" 0 64 expected)
    string(SUBSTRING "${entry}" 65 -1 path)
    if(IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)\\.\\.(/|$)")
      message(FATAL_ERROR "Invalid WASM SDK manifest path")
    endif()
    file(SHA256 "${sdk}/${path}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "WASM SDK file changed: ${path}")
    endif()
  endforeach()
endfunction()
